version: v1

labels:
  - label: build
    sync: true
    matcher:
      title: ^build(?:\([\w-]+\))?:.*
      branch: ^build[/-].*
      commits: ^build(?:\([\w-]+\))?:.*

  - label: build
    sync: true
    matcher:
      title: ^chore(?:\([\w-]+\))?:.*
      branch: ^chore[/-].*
      commits: ^chore(?:\([\w-]+\))?:.*

  - label: ci
    sync: true
    matcher:
      branch: ^ci[/-].*
      commits: ^ci(?:\([\w-]+\))?:.*
      files: .github/**

  - label: docs
    sync: true
    matcher:
      branch: ^docs[/-].*
      commits: ^docs(?:\([\w-]+\))?:.*

  - label: feature
    sync: true
    matcher:
      title: ^feat(?:\([\w-]+\))?:.*
      branch: ^feat[/-].*
      commits: ^feat(?:\([\w-]+\))?:.*

  - label: icons
    sync: true
    matcher:
      files: src/icons/*

  - label: lib
    sync: true
    matcher:
      files: src/lib/*

  - label: languages
    sync: true
    matcher:
      files: src/languages/*

  - label: fix
    sync: true
    matcher:
      branch: ^fix[/-].*
      commits: ^fix(?:\([\w-]+\))?:.*

  - label: performance
    sync: true
    matcher:
      branch: ^perf[/-].*
      commits: ^perf(?:\([\w-]+\))?:.*

  - label: plugins
    sync: true
    matcher:
      files: src/plugins/*

  - label: refactor
    sync: true
    matcher:
      branch: ^refactor[/-].*
      commits: ^refactor(?:\([\w-]+\))?:.*

  - label: style
    sync: true
    matcher:
      branch: ^style[/-].*
      commits: ^style(?:\([\w-]+\))?:.*

  - label: test
    sync: true
    matcher:
      branch: ^test[/-].*
      commits: ^test(?:\([\w-]+\))?:.*
      files: test/**

  - label: themes
    sync: true
    matcher:
      files: src/themes/**
