name: Node.js CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm -v
    - run: npm ci
    - run: npm t
